name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: runcycles/.github/.github/workflows/ci-typescript.yml@21844c8f796cd77ca5cf8bf0eae4f6f22e7782a0 # main
    with:
      run-lint: true
