name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: runcycles/.github/.github/workflows/ci-typescript.yml@6170a69465411c59192be83b8844bba4664a6b4c # main
    with:
      run-lint: true
